using UnityEngine;
using UnityEngine.SceneManagement;
using UnityEngine.AI;
using System.Collections.Generic;

namespace StealthHuntAI
{
    /// <summary>
    /// Marks an area as an interesting search region for the HuntDirector.
    /// Place on empty GameObjects in rooms, corridors and choke points.
    ///
    /// If no PatrolRegions exist in the scene the Director auto-generates
    /// regions from NavMesh sampling at startup.
    ///
    /// Tips:
    ///   - Place one per room or major area
    ///   - Larger radius = lower search priority (more area to cover)
    ///   - Use interestBias to mark high-value areas (exits, objectives)
    /// </summary>
    [AddComponentMenu("StealthHuntAI/Patrol Region")]
    public class PatrolRegion : MonoBehaviour
    {
        // ---------- Inspector -------------------------------------------------

        [Tooltip("Search radius of this region in world units.")]
        [Range(2f, 30f)] public float radius = 8f;

        [Tooltip("Extra interest weight. Higher = Director sends units here more often.")]
        [Range(0.1f, 3f)] public float interestBias = 1f;

        [Tooltip("If true this region is always considered regardless of player position.")]
        public bool alwaysActive = false;

        // ---------- Runtime ---------------------------------------------------

        /// <summary>Current interest score. Updated by HuntDirector each tick.</summary>
        public float CurrentScore { get; set; }

        /// <summary>Time.time when a unit was last sent to this region.</summary>
        public float LastVisitTime { get; set; } = -999f;

        /// <summary>How long since this region was last visited.</summary>
        public float TimeSinceVisit => Time.time - LastVisitTime;

        // ---------- Static registry ------------------------------------------

        private static readonly List<PatrolRegion> _all = new List<PatrolRegion>();

        public static IReadOnlyList<PatrolRegion> All => _all;

        private void OnEnable()
        {
            if (!_all.Contains(this))
                _all.Add(this);
        }

        private void OnDestroy() { _all.Remove(this); }

        [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.SubsystemRegistration)]
        private static void DomainReload() { _all.Clear(); }

        private void OnDisable()
        {
            _all.Remove(this);
        }


        // ---------- Auto-generation flag ------------------------------------

        /// <summary>True if this region was auto-generated by HuntDirector
        /// from NavMesh sampling rather than placed manually.</summary>
        public bool IsAutoGenerated { get; internal set; }

        // ---------- Learning data --------------------------------------------

        private int _playerFoundCount;
        private int _searchCount;

        /// <summary>Record that the player was found near this region.</summary>
        public void RecordPlayerFound()
        {
            _playerFoundCount++;
            // Boost interest when player is found here -- guards return sooner
            interestBias = Mathf.Min(3f, interestBias + 0.2f);
            LastVisitTime = Time.time;
        }

        /// <summary>Record that a guard searched this region.</summary>
        public void RecordSearch()
        {
            _searchCount++;
            LastVisitTime = Time.time;
        }

        /// <summary>Reset learning data -- called when player is lost.</summary>
        public void ResetLearning()
        {
            _playerFoundCount = 0;
            _searchCount = 0;
        }

        // ---------- Scoring --------------------------------------------------

        /// <summary>
        /// Score this region for a given player last known position and flight vector.
        /// Higher score = more likely Director sends a unit here.
        /// </summary>
        public float Evaluate(Vector3 playerLastKnown, Vector3 flightVector,
                               float maxRange)
        {
            Vector3 toRegion = transform.position - playerLastKnown;
            float dist = toRegion.magnitude;

            if (dist > maxRange && !alwaysActive) return 0f;

            // Distance score -- closer to last known = higher
            float distScore = 1f - Mathf.Clamp01(dist / maxRange);

            // Flight alignment -- regions in escape direction score higher
            float flightScore = 0.5f;
            if (flightVector.magnitude > 0.1f)
            {
                float dot = Vector3.Dot(flightVector.normalized, toRegion.normalized);
                flightScore = Mathf.Clamp01(dot * 0.5f + 0.5f);
            }

            // Recency -- regions not recently visited score higher
            float recencyScore = Mathf.Clamp01(TimeSinceVisit / 30f);

            return (distScore * 0.35f
                  + flightScore * 0.35f
                  + recencyScore * 0.20f)
                  * interestBias;
        }

        // ---------- Gizmos ---------------------------------------------------

        private void OnDrawGizmos()
        {
            Gizmos.color = new Color(0.8f, 0.5f, 0.1f, 0.08f);
            Gizmos.DrawSphere(transform.position, radius);
            Gizmos.color = new Color(0.8f, 0.5f, 0.1f, 0.35f);
            Gizmos.DrawWireSphere(transform.position, radius);

#if UNITY_EDITOR
            if (Application.isPlaying && CurrentScore > 0.01f)
            {
                UnityEditor.Handles.color = new Color(0.8f, 0.5f, 0.1f, 0.8f);
                UnityEditor.Handles.Label(
                    transform.position + Vector3.up * (radius * 0.3f + 0.5f),
                    gameObject.name + " " + CurrentScore.ToString("F2"));
            }
            else
            {
                UnityEditor.Handles.color = new Color(0.6f, 0.4f, 0.1f, 0.5f);
                UnityEditor.Handles.Label(
                    transform.position + Vector3.up * (radius * 0.3f + 0.5f),
                    gameObject.name);
            }
#endif
        }
    }
}